//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebBird.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_user_catch_fly
    {
        public string mno { get; set; }
        public string mname { get; set; }
        public int mtel { get; set; }
        public string mconn { get; set; }
        public string memail { get; set; }
        public int mtype { get; set; }
        public string catchno { get; set; }
        public string mid { get; set; }
        public string mid2 { get; set; }
        public string mspecies { get; set; }
        public string mcolor { get; set; }
        public string mfeature { get; set; }
        public string maddr { get; set; }
        public string maddr_detail { get; set; }
        public decimal lat { get; set; }
        public decimal lng { get; set; }
        public System.DateTime mdate { get; set; }
        public System.DateTime mdate_edit { get; set; }
        public string mremark { get; set; }
        public string mstate { get; set; }
        public bool edit { get; set; }
    }
}
