//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebBird.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_user_road
    {
        public string mno { get; set; }
        public string mid { get; set; }
        public string Expr1 { get; set; }
        public string memail { get; set; }
        public Nullable<int> mtel { get; set; }
        public string mconn { get; set; }
        public string roadtol { get; set; }
        public int road_id { get; set; }
    }
}
