//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebBird.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webbirdEntities : DbContext
    {
        public webbirdEntities()
            : base("name=webbirdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<z_bas_bird> z_bas_bird { get; set; }
        public virtual DbSet<z_bas_user> z_bas_user { get; set; }
        public virtual DbSet<z_func_catch> z_func_catch { get; set; }
        public virtual DbSet<z_func_fly> z_func_fly { get; set; }
        public virtual DbSet<z_func_see> z_func_see { get; set; }
        public virtual DbSet<z_func_see_d> z_func_see_d { get; set; }
        public virtual DbSet<z_sys_addr_city> z_sys_addr_city { get; set; }
        public virtual DbSet<z_sys_addr_city_area> z_sys_addr_city_area { get; set; }
        public virtual DbSet<z_sys_addr_city_area_road> z_sys_addr_city_area_road { get; set; }
        public virtual DbSet<z_sys_species> z_sys_species { get; set; }
        public virtual DbSet<z_sys_state> z_sys_state { get; set; }
        public virtual DbSet<z_sys_type_size> z_sys_type_size { get; set; }
        public virtual DbSet<z_sys_type_size_genus> z_sys_type_size_genus { get; set; }
        public virtual DbSet<z_sys_type_size_genus_species> z_sys_type_size_genus_species { get; set; }
        public virtual DbSet<z_sys_type_size_genus_species_color> z_sys_type_size_genus_species_color { get; set; }
        public virtual DbSet<vi_funcUNION> vi_funcUNION { get; set; }
        public virtual DbSet<vi_user_catch> vi_user_catch { get; set; }
        public virtual DbSet<vi_user_fly> vi_user_fly { get; set; }
    }
}
