//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebBird.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_func_catch
    {
        public int rowid { get; set; }
        public string user_no { get; set; }
        public string mno { get; set; }
        public string mid { get; set; }
        public string mid2 { get; set; }
        public string show_id { get; set; }
        public string mspecies { get; set; }
        public string mcolor { get; set; }
        public string mfeature { get; set; }
        public string maddr { get; set; }
        public string maddr_detail { get; set; }
        public string maddr_content { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lng { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
        public Nullable<System.DateTime> mtime { get; set; }
        public Nullable<System.DateTime> mdate_edit { get; set; }
        public Nullable<System.DateTime> mdate_create { get; set; }
        public string mremarks { get; set; }
        public string mstate { get; set; }
        public Nullable<bool> edit { get; set; }
        public string filepath { get; set; }
    }
}
